 /* == Rulebook == */
 /* Model Rules */
 /* Universal */
Battle\ Standard\ Bearer printf("Armeestandartentraeger");
Wizard\ Adept printf("Zauberadept");

 /* Command Group */
Musician printf("Musiker");
Standard\ Bearer printf("Standartentraeger");

 /* Armour */
Light\ Armour printf("leichte Ruestung");
Shield printf("Schild");

 /* Weapons */
Spear printf("Speer");
Great\ Weapon printf("Zweihandwaffe");
Halberd printf("Hellebarde");

